config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  root to: 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
    :registerable,
    :recoverable, 
    :rememberable, 
    :trackable, 
    :validatable,
    :confirmable,
    :lockable,
    :timeoutable
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_footer.html.haml
.navbar.navbar-default
  .container
    .navbar-text footer

app/views/application/_menu.html.haml
.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{type: :button, 
        'data-toggle' => :collapse, 
        'data-target' => '.navbar-collapse'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} devpad.me
    .collapse.navbar-collapse
      = render 'menu_nav'
      = render 'menu_user'

app/views/application/_menu_link.html.haml
%li
  = link_to locals[:label] || locals[:href], 
    locals[:href], 
    method: locals[:method] || :get,
    class: "glyphicon glyphicon-#{locals[:icon]|| 'link'}"

app/views/application/_menu_nav.html.haml
%ul.nav.navbar-nav
  = render 'menu_link', locals:{ href: contact_path, label: 'Contact', icon: 'envelope'}
  = render 'menu_link', locals:{ href: about_path, label: 'About', icon: 'star' }
  = #render 'menu_link', locals:{ href: 'dummy/nothing' }

app/views/application/_menu_nav_item.html.haml
%li
  = link_to locals[:label] || locals[:href], 
    locals[:href], 
    method: locals[:method] || :get,
    class: "glyphicon glyphicon-#{locals[:icon]|| 'link'}"

app/views/application/_menu_user.html.haml
%ul.nav.navbar-nav.navbar-right
  = render account_signed_in? ? 'menu_user_signed_in' :  'menu_user_unsigned'

app/views/application/_menu_user_signed_in.html.haml
= render 'menu_link',
  locals: { href: '',
    label: current_account.email,
    icon: 'user'}
= render 'menu_link', 
  locals: { href: destroy_account_session_path,
    method: :delete, 
    label: "Sign out", 
    icon: 'log-out' }

app/views/application/_menu_user_unsigned.html.haml
= render 'menu_link', 
  locals: { href: new_account_session_path, 
    label: "Sign in", 
    icon: 'log-in' }
= render 'menu_link', 
  locals: { href: new_account_registration_path, 
    label: 'Sign up', 
    icon: 'plus' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield(:title)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #wrap
      = render 'menu'
      
      .jumbotron
        .container
          %h1= content_for?(:title) ? yield(:title) : 'DevPad.me'

      .container#main{role: :main}
        .row
          .col-md-12= yield

    .footer
      = render 'footer'

app/views/pages/about.html.haml
- content_for :title do
  About me
%p About

%p About me :-)

app/views/pages/contact.html.haml
- content_for :title do
  Contact information
%p Contact

%p contact information

app/views/pages/home.html.haml
%p Home page

%p= (0...50).inject(' '){|sum,e|sum+=('a'...'z').to_a.join[0...rand(26)]+' '}